export class LogUser{
  idCocinero: number;
  nombreCocinero: string;
  apellidoPaterno: string;
  apellidoMaterno: string;
  nombreCompleto: string;
  genero: string;
  redesSocialesConfig: boolean;
  hubConfigurado: boolean;
  bancoConfig: boolean;
  idEstablecimiento: number;
  cveEstablecimiento: string;
  nombreEstablecimiento: string;
  tipoNegocio: string;
  numTelefono: string;
  calle: string;
  entreCalles: string;
  comentarios: string;
  colonia: string;
  ciudad: string;
  idEstado: number;
  pais: string;
  cp: string;
  numero: string;
  tipoVehiculo: string;
  calificacion: string;
  correo : string;
  nombrePais : string;
  nombreEstado : string;
  nombreMunicipio : string;
  ubicacionCompleta : string;
}